### ISSUE TITLE
Autenticación en API con JWT

### ISSUE THREAD

**Issue by matiasrohleder** [matiasrohleder/MyPrayer#14]
Como desarrollador de la API, quiero implementar un sistema de autenticación basado en tokens JWT (JSON Web Tokens) para garantizar la seguridad y la autorización de los usuarios al acceder a los recursos protegidos de la API. La user story implica lo siguiente:

Generación de Tokens JWT: Desarrollar un mecanismo para generar tokens JWT válidos después de que un usuario se autentique correctamente en la API utilizando sus credenciales.

Verificación de Credenciales: Validar las credenciales del usuario durante el proceso de autenticación para garantizar que solo los usuarios registrados y autorizados puedan obtener un token JWT.

Protección de Endpoints: Configurar la API para que ciertos endpoints y recursos requieran un token JWT válido para acceder, asegurando que solo los usuarios autenticados puedan realizar ciertas operaciones.

**Comment by camiguardia** [comment]
Tome una sugerencia de @fekabas para cambiar los tokens por una ApiKey.
